version: '3'
services:
  app:
    build: .
    ports:
      - '3554:3554'
    environment:
      - PORT=3554
      - PUBLIC_SUPABASE_URL=${PUBLIC_SUPABASE_URL}
      - PUBLIC_SUPABASE_ANON_KEY=${PUBLIC_SUPABASE_ANON_KEY}
    restart: unless-stopped
